modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="crates"
version="1.2.0"
displayName="Crates"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="WenXin2"
description='''
Crates! Nothing more, nothing less.
'''

[[dependencies.crates]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




